### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/argos-mouse#1]
- [x] SMD breakout pads in the back
- [x] pin holes in f360 model to check choc placement
- [x] spaghetti type connections on flex pcb
- [x] model usb hole in switch assembly
- [x] reverse flexplate connector on controller board
- [x] make controller board longer (5mm)
- [x] change SCK (GP22/SPI0) to eg. GP14/SPI1
- [ ] argos-controller: rename project files

**Comment by bstiq** [comment]
closed, moved the last point to #3
