### ISSUE TITLE
3d models todo

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/argos-mouse#5]
- [ ] 2nd screw on trackpad holder
- [ ] guide for trackpad cable so it doesn't go out switch holder
- [ ] make switch pcb headers more accessible from the top
- [ ] Make screw controller more accessible
